[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://gcadr.netlify.app/.netlify/functions"
  NEXT_PUBLIC_SITE_URL = "https://gcadr.netlify.app"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
