services:
  - type: web
    name: gcadr-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_superuser"
    startCommand: "cd backend && gunicorn gcadr_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gcadr-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "gcadr-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://gcadr.vercel.app"
      - key: PYTHON_VERSION
        value: "3.11.9"

databases:
  - name: gcadr-db
    databaseName: gcadr
    user: gcadr
    plan: free
