# Generated by Django 4.2.23 on 2025-08-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True, help_text='Brief bio for external authors'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Contact email for external authors', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, help_text='Use this for external or guest authors', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='author_name',
            field=models.CharField(blank=True, help_text='Use this for external organizers', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('convenor', 'Convenor'), ('co_convenor', 'Co-convenor'), ('secretary', 'Secretary'), ('co_secretary', 'Co-secretary'), ('treasurer', 'Treasurer'), ('co_treasurer', 'Co-Treasurer'), ('social_media_head', 'Social Media Head'), ('it_blog_head', 'IT and Blog Head'), ('research_outreach_head', 'Research and Outreach Head'), ('student_mentor', 'Student Mentor'), ('mediation_cell_head', 'Mediation Cell Head'), ('student_member', 'Student Member')], max_length=30),
        ),
    ]
