# Generated by Django 4.2.23 on 2025-08-04 18:20

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_author_bio_blogpost_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the post was/will be published'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Content in Markdown format'),
        ),
    ]
