# Generated by Django 4.2.23 on 2025-08-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_published_date_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
    ]
