# Generated by Django 4.2.23 on 2025-08-05 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issue_number', models.CharField(help_text="e.g., 'Issue 1, 2024'", max_length=50)),
                ('pdf_file', models.FileField(upload_to='newsletter_archives/')),
                ('published_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_date', 'order'],
            },
        ),
    ]
